name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    container: python:3.10-bullseye

    steps:
      - uses: actions/checkout@v3

      - name: Read Python version
        id: read-python-version
        run: echo "::set-output name=python-version::$(cat .python_version)"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.read-python-version.outputs.python-version }}

      - name: Install poetry
        run: |
          pip install poetry==1.4.0

      - name: Install project dependencies
        run: |
          poetry install

      - name: Build and deploy docs
        run: |
          # git config --global --add safe.directory /__w/noresm-land-sites-platform/noresm-land-sites-platform
          git config --global --add safe.directory /__w/noresm-temp-docs/noresm-temp-docs
          poetry run mkdocs gh-deploy --force